 DROP TABLE Countries;
 CREATE TABLE Countries (
Name                             Character(40));
insert into Countries values('Latin America');
insert into Countries values('Argentina (2006)');
insert into Countries values('Bolivia (2008)');
insert into Countries values('Brazil (2007)');
insert into Countries values('Chile (2007)');
insert into Countries values('Colombia (2006)');
insert into Countries values('Costa Rica (2007)');
insert into Countries values('Dominican Republic (2009)');
insert into Countries values('Ecuador (2007)');
insert into Countries values('El Salvador (2007)');
insert into Countries values('Guatemala (2009)');
insert into Countries values('Honduras (2008)');
insert into Countries values('Jamaica (2006)');
insert into Countries values('Mexico (2008)');
insert into Countries values('Paraguay (2007)');
insert into Countries values('Peru (2008)');
insert into Countries values('North America');
insert into Countries values('Canada (2007)');
insert into Countries values('USA (2008)');
insert into Countries values('Africa');
insert into Countries values('Benin (2007)');
insert into Countries values('Burkina faso (2007)');
insert into Countries values('Côte D''Ivoire (2007)');
insert into Countries values('Egypt (2007)');
insert into Countries values('Kenya (2007)');
insert into Countries values('Malawi (2007)');
insert into Countries values('Mali (2007)');
insert into Countries values('Mauritania (2008)');
insert into Countries values('Morocco (2007)');
insert into Countries values('Mozambique (2009)');
insert into Countries values('Niger (2007)');
insert into Countries values('Rwanda (2008)');
insert into Countries values('Senegal (2007)');
insert into Countries values('South Africa (2007)');
insert into Countries values('Tanzania (2007)');
insert into Countries values('Togo (2007)');
insert into Countries values('Tunisia (2008)');
insert into Countries values('Uganda (2007)');
insert into Countries values('Asia Pacific');
insert into Countries values('Australia (2008)');
insert into Countries values('Bangladesh (2007)');
insert into Countries values('Cambodia (2007)');
insert into Countries values('China (2008)');
insert into Countries values('Indonesia (2008)');
insert into Countries values('Japan (2008)');
insert into Countries values('Korea, Republic of (2006)');
insert into Countries values('Nepal (2008)');
insert into Countries values('New Zealand (2008)');
insert into Countries values('Pakistan (2009)');
insert into Countries values('Philippines (2009)');
