-- phpMyAdmin SQL Dump
-- version 3.3.10.2
-- http://www.phpmyadmin.net
--
-- Serveur: localhost
-- Généré le : Ven 09 Décembre 2011 à 05:20
-- Version du serveur: 5.0.91
-- Version de PHP: 5.2.6

SET SQL_MODE="NO_AUTO_VALUE_ON_ZERO";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;

--
-- Base de données: `uclggold_gold`
--

-- --------------------------------------------------------

--
-- Structure de la table `gold_content`
--

CREATE TABLE IF NOT EXISTS `gold_content` (
  `id` int(10) unsigned NOT NULL auto_increment,
  `asset_id` int(10) unsigned NOT NULL default '0' COMMENT 'FK to the #__assets table.',
  `title` varchar(255) NOT NULL default '',
  `alias` varchar(255) character set utf8 collate utf8_bin NOT NULL default '',
  `title_alias` varchar(255) character set utf8 collate utf8_bin NOT NULL default '' COMMENT 'Deprecated in Joomla! 3.0',
  `introtext` mediumtext NOT NULL,
  `fulltext` mediumtext NOT NULL,
  `state` tinyint(3) NOT NULL default '0',
  `sectionid` int(10) unsigned NOT NULL default '0',
  `mask` int(10) unsigned NOT NULL default '0',
  `catid` int(10) unsigned NOT NULL default '0',
  `created` datetime NOT NULL default '0000-00-00 00:00:00',
  `created_by` int(10) unsigned NOT NULL default '0',
  `created_by_alias` varchar(255) NOT NULL default '',
  `modified` datetime NOT NULL default '0000-00-00 00:00:00',
  `modified_by` int(10) unsigned NOT NULL default '0',
  `checked_out` int(10) unsigned NOT NULL default '0',
  `checked_out_time` datetime NOT NULL default '0000-00-00 00:00:00',
  `publish_up` datetime NOT NULL default '0000-00-00 00:00:00',
  `publish_down` datetime NOT NULL default '0000-00-00 00:00:00',
  `images` text NOT NULL,
  `urls` text NOT NULL,
  `attribs` varchar(5120) NOT NULL,
  `version` int(10) unsigned NOT NULL default '1',
  `parentid` int(10) unsigned NOT NULL default '0',
  `ordering` int(11) NOT NULL default '0',
  `metakey` text NOT NULL,
  `metadesc` text NOT NULL,
  `access` int(10) unsigned NOT NULL default '0',
  `hits` int(10) unsigned NOT NULL default '0',
  `metadata` text NOT NULL,
  `featured` tinyint(3) unsigned NOT NULL default '0' COMMENT 'Set if article is featured.',
  `language` char(7) NOT NULL COMMENT 'The language code for the article.',
  `xreference` varchar(50) NOT NULL COMMENT 'A reference to enable linkages to external data sets.',
  PRIMARY KEY  (`id`),
  KEY `idx_access` (`access`),
  KEY `idx_checkout` (`checked_out`),
  KEY `idx_state` (`state`),
  KEY `idx_catid` (`catid`),
  KEY `idx_createdby` (`created_by`),
  KEY `idx_featured_catid` (`featured`,`catid`),
  KEY `idx_language` (`language`),
  KEY `idx_xreference` (`xreference`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8 AUTO_INCREMENT=43 ;

--
-- Contenu de la table `gold_content`
--

INSERT INTO `gold_content` (`id`, `asset_id`, `title`, `alias`, `title_alias`, `introtext`, `fulltext`, `state`, `sectionid`, `mask`, `catid`, `created`, `created_by`, `created_by_alias`, `modified`, `modified_by`, `checked_out`, `checked_out_time`, `publish_up`, `publish_down`, `images`, `urls`, `attribs`, `version`, `parentid`, `ordering`, `metakey`, `metadesc`, `access`, `hits`, `metadata`, `featured`, `language`, `xreference`) VALUES
(5, 37, 'Decentralization and Local Democracy in the World', 'gold-reports-1', '', '<p>It is our great pleasure to present the “First Global Report on Decentralization and Local Democracy”. We hope this report, which is the first of its kind, will help broaden and deepen knowledge about the current role of local governments and enrich national and international discussion on the relationship between decentralization and development.</p>\r\n\r\n<p>This first GOLD Report, as we present it today, is part of the UCLG initiative to analyze the advances and possible reverses to local democracy and decentralization around the world on a regular basis. It is also the first global comparative analysis of the situation of local authorities in every region in the world.</p>\r\n\r\n<p><img style="display: block; margin-left: auto; margin-right: auto;" src="/images/stories/gold-reports/gold-reports-I.jpg" alt="" /></p>\r\n\r\n<p style="text-align: center;"><a class="read_full" onclick="window.open(this.href,'''',''scrollbars=yes,resizable=yes,location=yes,menubar=yes,status=yes,toolbar=yes,width=,height=,left=''+(screen.availWidth/2-0)+'',top=''+(screen.availHeight/2-0)+'''');return false;" href="http://issuu.com/uclggold/docs/gold_report_en?mode=embed">Read full report</a></p>\r\n\r\n', '', 1, 0, 0, 2, '2011-05-02 11:48:08', 42, '', '2011-11-14 14:48:51', 42, 0, '0000-00-00 00:00:00', '2011-05-02 11:48:08', '0000-00-00 00:00:00', '', '', '{"show_title":"","link_titles":"","show_intro":"","show_category":"","link_category":"","show_parent_category":"","link_parent_category":"","show_author":"","link_author":"","show_create_date":"","show_modify_date":"","show_publish_date":"","show_item_navigation":"","show_icons":"","show_print_icon":"","show_email_icon":"","show_vote":"","show_hits":"","show_noauth":"","alternative_readmore":"","article_layout":""}', 9, 0, 3, '', '', 1, 260, '{"robots":"","author":"","rights":"","xreference":""}', 0, '*', ''),
(23, 92, 'News Africa number 1', 'news-africa-number-1', '', '<p><img src="/images/stories/news/pellentesque.jpg" alt="" style="float: left; margin: 10px;" border="0" width="200px" /><span class="Apple-style-span" style="color: #363636; font-family: TitilliumText22LLight; font-size: 16px; line-height: 20px;">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam auctor, ipsum eget tincidunt pulvinar, tortor neque aliquam est, sit amet molestie turpis ligula in magna. Mauris venenatis mattis consequat. Pellentesque et ipsum lectus. Ut egestas sollicitudin posuere. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.Morbi in tellus nec metus dapibus sagittis sed sed nisi. Proin velit lacus, ultricies eu euismod et, bibendum id lectus. Praesent congue sollicitudin augue, ut posuere ligula elementum id. Sed convallis, arcu porttitor blandit tincidunt, odio dui sagittis dolor, id volutpat purus ipsum euismod lacus. In pulvinar odio et nulla accumsan aliquet. Vestibulum sed vestibulum tellus. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vestibulum nunc massa, varius sit amet dictum a, vestibulum sit amet dui.</span></p>', '', 1, 0, 0, 43, '2011-11-08 13:47:16', 42, '', '2011-11-17 18:10:31', 42, 0, '0000-00-00 00:00:00', '2011-11-08 13:47:16', '0000-00-00 00:00:00', '', '', '{"show_title":"","link_titles":"","show_intro":"","show_category":"","link_category":"","show_parent_category":"","link_parent_category":"","show_author":"","link_author":"","show_create_date":"","show_modify_date":"","show_publish_date":"","show_item_navigation":"","show_icons":"","show_print_icon":"","show_email_icon":"","show_vote":"","show_hits":"","show_noauth":"","alternative_readmore":"","article_layout":""}', 7, 0, 2, '', '', 1, 29, '{"robots":"","author":"","rights":"","xreference":""}', 0, '*', ''),
(24, 93, 'News Asia Pacific number 1 ', 'news-asia-pacific-1', '', '<p><img src="/images/stories/news/pellentesque.jpg" border="0" alt="" width="200px" style="float: left;margin:10px" /><span class="Apple-style-span" style="color: #363636; font-family: TitilliumText22LLight; font-size: 16px; line-height: 20px;">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam auctor, ipsum eget tincidunt pulvinar, tortor neque aliquam est, sit amet molestie turpis ligula in magna. Mauris venenatis mattis consequat. Pellentesque et ipsum lectus. Ut egestas sollicitudin posuere. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Morbi in tellus nec metus dapibus sagittis sed sed nisi. Proin velit lacus, ultricies eu euismod et, bibendum id lectus. Praesent congue sollicitudin augue, ut posuere ligula elementum id. Sed convallis, arcu porttitor blandit tincidunt, odio dui sagittis dolor, id volutpat purus ipsum euismod lacus. In pulvinar odio et nulla accumsan aliquet. Vestibulum sed vestibulum tellus. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vestibulum nunc massa, varius sit amet dictum a, vestibulum sit amet dui.</span></p>', '', 1, 0, 0, 42, '2011-11-08 13:47:16', 42, '', '2011-11-17 18:11:12', 42, 0, '0000-00-00 00:00:00', '2011-11-08 13:47:16', '0000-00-00 00:00:00', '', '', '{"show_title":"","link_titles":"","show_intro":"","show_category":"","link_category":"","show_parent_category":"","link_parent_category":"","show_author":"","link_author":"","show_create_date":"","show_modify_date":"","show_publish_date":"","show_item_navigation":"","show_icons":"","show_print_icon":"","show_email_icon":"","show_vote":"","show_hits":"","show_noauth":"","alternative_readmore":"","article_layout":""}', 4, 0, 1, '', '', 1, 5, '{"robots":"","author":"","rights":"","xreference":""}', 0, '*', ''),
(25, 95, 'News America', 'news-america', '', '<p><img src="/images/stories/news/pellentesque.jpg" border="0" alt="" width="200px" style="float: left;margin:10px" /><span class="Apple-style-span" style="color: #363636; font-family: TitilliumText22LLight; font-size: 16px; line-height: 20px;">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam auctor, ipsum eget tincidunt pulvinar, tortor neque aliquam est, sit amet molestie turpis ligula in magna. Mauris venenatis mattis consequat. Pellentesque et ipsum lectus. Ut egestas sollicitudin posuere. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Morbi in tellus nec metus dapibus sagittis sed sed nisi. Proin velit lacus, ultricies eu euismod et, bibendum id lectus. Praesent congue sollicitudin augue, ut posuere ligula elementum id. Sed convallis, arcu porttitor blandit tincidunt, odio dui sagittis dolor, id volutpat purus ipsum euismod lacus. In pulvinar odio et nulla accumsan aliquet. Vestibulum sed vestibulum tellus. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vestibulum nunc massa, varius sit amet dictum a, vestibulum sit amet dui.</span></p>', '', 1, 0, 0, 44, '2011-11-08 13:47:16', 42, '', '2011-11-17 18:10:50', 42, 0, '0000-00-00 00:00:00', '2011-11-08 13:47:16', '0000-00-00 00:00:00', '', '', '{"show_title":"","link_titles":"","show_intro":"","show_category":"","link_category":"","show_parent_category":"","link_parent_category":"","show_author":"","link_author":"","show_create_date":"","show_modify_date":"","show_publish_date":"","show_item_navigation":"","show_icons":"","show_print_icon":"","show_email_icon":"","show_vote":"","show_hits":"","show_noauth":"","alternative_readmore":"","article_layout":""}', 6, 0, 0, '', '', 1, 1, '{"robots":"","author":"","rights":"","xreference":""}', 0, '*', ''),
(26, 97, 'Section Africa', 'section-africa', '', '<!?php \r\n// on envoie un cookie de nom uclg_section portant la valeur africa d''une durée de validité de 7 jours\r\nsetcookie ("uclg_section", "africa", time() + 365 * 7 * 24); \r\n?>', '', -2, 0, 0, 8, '2011-11-09 14:17:18', 42, '', '2011-11-09 15:02:02', 42, 0, '0000-00-00 00:00:00', '2011-11-09 14:17:18', '0000-00-00 00:00:00', '', '', '{"show_title":"","link_titles":"","show_intro":"","show_category":"","link_category":"","show_parent_category":"","link_parent_category":"","show_author":"","link_author":"","show_create_date":"","show_modify_date":"","show_publish_date":"","show_item_navigation":"","show_icons":"","show_print_icon":"","show_email_icon":"","show_vote":"","show_hits":"","show_noauth":"","alternative_readmore":"","article_layout":""}', 2, 0, 0, '', '', 1, 0, '{"robots":"","author":"","rights":"","xreference":""}', 0, '*', ''),
(30, 102, 'About', 'about', '', '<h3>Global Observatory on Local Democracy and Decentralization</h3>\r\n<p>The Global Observatory on Local Democracy and Decentralization (GOLD) was launched by UCLG in 2006 as part of its objective to become a main source of information on local self-government, local authorities, governance, local democracy and the exchange of know-how. GOLD provides information on the state of decentralization and its evolution, self-government and local governance across the world. </p>\r\n<p>The Global Observatory and its regional chapters provide information, documents, data bases and links useful to local governments in each of the world regions, and can be accesses from the GOLD Home page.</p>\r\n<p>The GOLD portal also allows access to UCLG’s “Global Reports on Decentralization and Local Democracy” published every three years.  The first of these reports was launched by UCLG in October 2007 in time for the 2nd World Congress in Jeju, South Korea. The second report, GOLD II focused on Local finance and was launched during the 3rd UCLG World Congress held in Mexico DC November 2010. </p>\r\n<p>The site also provides access to other relevant publications and information such as regional and thematic reports, country profiles which summarize the situation of local government in over 70 countries, key statistics on local governments worldwide, a Virtual library and database of websites with relevant information both general and regional on local government.The portal has been developed in partnership with UCLG’s Regional and Metropolitan Sections and new links and information are being continually added.</p>\r\n<br>\r\n<p style="text-align: center;"><img src="/images/stories/about/logo_uclg_about.jpg" border="0" /></p>', '', 1, 0, 0, 46, '2011-11-09 19:40:55', 42, '', '2011-12-02 22:51:27', 42, 0, '0000-00-00 00:00:00', '2011-11-09 19:40:55', '0000-00-00 00:00:00', '', '', '{"show_title":"0","link_titles":"0","show_intro":"0","show_category":"0","link_category":"0","show_parent_category":"0","link_parent_category":"0","show_author":"0","link_author":"0","show_create_date":"0","show_modify_date":"0","show_publish_date":"0","show_item_navigation":"0","show_icons":"0","show_print_icon":"0","show_email_icon":"0","show_vote":"0","show_hits":"0","show_noauth":"0","alternative_readmore":"","article_layout":""}', 6, 0, 0, '', '', 1, 17, '{"robots":"","author":"","rights":"","xreference":""}', 0, 'en-GB', ''),
(27, 98, 'Section Africa', 'article-section-africa', '', '<div class="moduletable">\r\n          <h3>Services</h3>\r\n  <ul id="mainlevelservices"><li><img src="/images/stories/gold_li.jpg" border="0" alt="GOLD Reports"/> <a href="/gold-reports" class="mainlevelservices" >GOLD Reports<span class="descripction">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec dapibus mi quis tortor consectetur eu eleifend purus tempus</span></a></li><li><img src="/images/stories/key_li.jpg" border="0" alt="Key Indicators"/> <a href="/key-indicators" class="mainlevelservices" >Key Indicators<span class="descripction">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec dapibus mi quis tortor consectetur eu eleifend purus tempus</span></a></li><li><img src="/images/stories/country_li.jpg" border="0" alt="Country Profiles"/> <a href="/country-profiles" class="mainlevelservices" >Country Profiles<span class="descripction">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec dapibus mi quis tortor consectetur eu eleifend purus tempus</span></a></li><li><img src="/images/stories/links_li.jpg" border="0" alt="Links Database"/> <a href="/links-database" class="mainlevelservices" >Links Database<span class="descripction">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec dapibus mi quis tortor consectetur eu eleifend purus tempus</span></a></li><li><img src="/images/stories/virtual_li.jpg" border="0" alt="Virtual Library"/> <a href="/virtual-library" class="mainlevelservices" >Virtual Library<span class="descripction">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec dapibus mi quis tortor consectetur eu eleifend purus tempus</span></a></li></ul>    </div>', '', -2, 0, 0, 49, '2011-11-09 15:13:38', 42, '', '2011-11-17 22:38:59', 42, 0, '0000-00-00 00:00:00', '2011-11-09 15:13:38', '0000-00-00 00:00:00', '', '', '{"show_title":"","link_titles":"","show_intro":"","show_category":"","link_category":"","show_parent_category":"","link_parent_category":"","show_author":"","link_author":"","show_create_date":"","show_modify_date":"","show_publish_date":"","show_item_navigation":"","show_icons":"","show_print_icon":"","show_email_icon":"","show_vote":"","show_hits":"","show_noauth":"","alternative_readmore":"","article_layout":""}', 62, 0, 1, '', '', 1, 518, '{"robots":"","author":"","rights":"","xreference":""}', 0, '*', ''),
(28, 99, 'Section Asia Pacific', 'article-section-asia-pacific', '', '<div class="moduletable">\r\n          <h3>Services</h3>\r\n  <ul id="mainlevelservices"><li><img src="/images/stories/gold_li.jpg" border="0" alt="GOLD Reports" /> <a href="/gold-reports" class="mainlevelservices">GOLD Reports<span class="descripction">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec dapibus mi quis tortor consectetur eu eleifend purus tempus</span></a></li><li><img src="/images/stories/key_li.jpg" border="0" alt="Key Indicators" /> <a href="/key-indicators" class="mainlevelservices">Key Indicators<span class="descripction">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec dapibus mi quis tortor consectetur eu eleifend purus tempus</span></a></li><li><img src="/images/stories/country_li.jpg" border="0" alt="Country Profiles" /> <a href="/country-profiles?profile=asiapacific" class="mainlevelservices">Country Profiles<span class="descripction">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec dapibus mi quis tortor consectetur eu eleifend purus tempus</span></a></li><li><img src="/images/stories/links_li.jpg" border="0" alt="Links Database" /> <a href="/links-database" class="mainlevelservices">Links Database<span class="descripction">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec dapibus mi quis tortor consectetur eu eleifend purus tempus</span></a></li><li><img src="/images/stories/virtual_li.jpg" border="0" alt="Virtual Library" /> <a href="/virtual-library" class="mainlevelservices">Virtual Library<span class="descripction">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec dapibus mi quis tortor consectetur eu eleifend purus tempus</span></a></li></ul>    \r\n</div>', '', -2, 0, 0, 49, '2011-11-09 15:13:38', 42, '', '2011-11-18 16:08:41', 43, 0, '0000-00-00 00:00:00', '2011-11-09 15:13:38', '0000-00-00 00:00:00', '', '', '{"show_title":"","link_titles":"","show_intro":"","show_category":"","link_category":"","show_parent_category":"","link_parent_category":"","show_author":"","link_author":"","show_create_date":"","show_modify_date":"","show_publish_date":"","show_item_navigation":"","show_icons":"","show_print_icon":"","show_email_icon":"","show_vote":"","show_hits":"","show_noauth":"","alternative_readmore":"","article_layout":""}', 24, 0, 0, '', '', 1, 326, '{"robots":"","author":"","rights":"","xreference":""}', 0, '*', ''),
(35, 116, 'News Africa number 2', 'news-africa-number-2', '', '<p><img src="http://www.cities-localgovernments.org/upload/img_news/9766409655_pa050029.jpg" alt="" style="float: left; margin: 10px;" border="0" width="200px" /><span class="Apple-style-span" style="color: #363636; font-family: TitilliumText22LLight; font-size: 16px; line-height: 20px;">New Africa 2</span></p>', '', 1, 0, 0, 43, '2011-11-08 13:47:16', 42, '', '2011-11-17 18:10:15', 42, 0, '0000-00-00 00:00:00', '2011-11-08 13:47:16', '0000-00-00 00:00:00', '', '', '{"show_title":"","link_titles":"","show_intro":"","show_category":"","link_category":"","show_parent_category":"","link_parent_category":"","show_author":"","link_author":"","show_create_date":"","show_modify_date":"","show_publish_date":"","show_item_navigation":"","show_icons":"","show_print_icon":"","show_email_icon":"","show_vote":"","show_hits":"","show_noauth":"","alternative_readmore":"","article_layout":""}', 3, 0, 1, '', '', 1, 4, '{"robots":"","author":"","rights":"","xreference":""}', 0, '*', ''),
(29, 100, 'Services', 'article-services', '', '<div class="moduletable">\r\n	<h3>Services\r\n	</h3>\r\n	<ul id="mainlevelservices">\r\n		<li><img alt="GOLD Reports" border="0" src="/images/stories/gold_li.jpg" /> <a class="mainlevelservices" href="/gold-reports">GOLD Reports<span class="descripction">The Global Report on Decentralization and Local Democracy provide a comparative analysis on local governance issues in each of the world regions.</span></a>\r\n		</li>\r\n		<li><img alt="Key Indicators" border="0" src="/images/stories/key_li.jpg" /> <a class="mainlevelservices" href="/key-indicators">Key Indicators<span class="descripction">Basic facts on local government in 95 selected countries </span></a>\r\n		</li>\r\n		<li><img alt="Country Profiles" border="0" src="/images/stories/country_li.jpg" /> <a class="mainlevelservices" href="/country-profiles">Country Profiles<span class="descripction">The &ldquo;Country Profiles&rdquo; provide a overview of the state of decentralization and local democracy in over 70 countries</span></a>\r\n		</li>\r\n		<li><img alt="Links Database" border="0" src="/images/stories/links_li.jpg" /> <a class="mainlevelservices" href="/links-database">Links Database<span class="descripction">Set of websites of interest to local governments from the various world regions </span></a>\r\n		</li>\r\n		<li><img alt="Virtual Library" border="0" src="/images/stories/virtual_li.jpg" /> <a class="mainlevelservices" href="/virtual-library">Virtual Library<span class="descripction">Publications, documents, videos about or of interest to local government</span></a>\r\n		</li>\r\n	</ul>\r\n</div>\r\n', '', 1, 0, 0, 49, '2011-11-09 15:13:38', 42, '', '2011-12-05 23:04:36', 42, 0, '0000-00-00 00:00:00', '2011-11-09 15:13:38', '0000-00-00 00:00:00', '', '', '{"show_title":"","link_titles":"","show_intro":"","show_category":"","link_category":"","show_parent_category":"","link_parent_category":"","show_author":"","link_author":"","show_create_date":"","show_modify_date":"","show_publish_date":"","show_item_navigation":"","show_icons":"","show_print_icon":"","show_email_icon":"","show_vote":"","show_hits":"","show_noauth":"","alternative_readmore":"","article_layout":""}', 29, 0, 0, '', '', 1, 1375, '{"robots":"","author":"","rights":"","xreference":""}', 0, '*', ''),
(31, 105, 'Virtual Library', 'virtual-library', '', '<p>This is a reference tool for the local governments.\r\n</p>\r\n<p>The Virtual Municipal Library, created by FLACMA UCLG&rsquo;s Latin American section, has been created to make available online, studies, laws and regulations, manuals, project, films about or of interest to local government.\r\n</p>\r\n<p>The Library is designed to allow those interested and implicated in municipal issues &ndash; local elected officials and technicians &ndash; to participate directly in its construction through contributing published and unpublished works.\r\n</p>\r\n<p>The library is in several languages. First find the language in which you want to make your search. Then, open and read the document in that folder called &quot;Read this first&quot;.\r\n</p>\r\n<p>Good browsing! FLACMA and UCLG\r\n</p>\r\n<p style="text-align: center;"><a href="http://www.bibliotecamunicipal.org/"><img alt="" border="0" src="/images/stories/library/biblioteca_virtual.jpg" /></a>\r\n</p>\r\n<p style="text-align: center;">Click on the logo to access the library\r\n</p>\r\n', '', 1, 0, 0, 29, '2011-11-10 16:25:02', 42, '', '2011-12-07 15:59:07', 42, 42, '2011-12-07 15:59:07', '2011-11-10 16:25:02', '0000-00-00 00:00:00', '', '', '{"show_title":"","link_titles":"","show_intro":"","show_category":"","link_category":"","show_parent_category":"0","link_parent_category":"","show_author":"","link_author":"0","show_create_date":"","show_modify_date":"","show_publish_date":"","show_item_navigation":"","show_icons":"","show_print_icon":"","show_email_icon":"","show_vote":"","show_hits":"","show_noauth":"","alternative_readmore":"","article_layout":""}', 10, 0, 0, '', '', 1, 38, '{"robots":"","author":"","rights":"","xreference":""}', 0, '*', ''),
(32, 107, 'Decentralization and Local Democracy in Africa', 'gold-reports-africa-1', '', '<p>It is our great pleasure to present the “First Global Report on Decentralization and Local Democracy” for Africa. We hope this report, which is the first of its kind, will help broaden and deepen knowledge about the current role of local governments and enrich national and international discussion on the relationship between decentralization and development.</p>\r\n\r\n<p>This first GOLD Africa Report, as we present it today, is part of the UCLG initiative to analyze the advances and possible reverses to local democracy and decentralization around the world on a regular basis. It is also the first global comparative analysis of the situation of local authorities in every region in the world.</p>\r\n\r\n<p><img style="display: block; margin-left: auto; margin-right: auto;" src="/images/stories/gold-reports/gold-reports-I.jpg" alt="" /></p>\r\n\r\n<p style="text-align: center;"><a class="read_full" onclick="window.open(this.href,'''',''scrollbars=yes,resizable=yes,location=yes,menubar=yes,status=yes,toolbar=yes,width=,height=,left=''+(screen.availWidth/2-0)+'',top=''+(screen.availHeight/2-0)+'''');return false;" href="http://issuu.com/uclggold/docs/gold_report_en?mode=embed">Read full report</a></p>', '', 1, 0, 0, 8, '2011-11-10 22:38:12', 42, '', '2011-11-16 01:27:36', 42, 0, '0000-00-00 00:00:00', '2011-11-10 22:38:12', '0000-00-00 00:00:00', '', '', '{"show_title":"","link_titles":"","show_intro":"","show_category":"","link_category":"","show_parent_category":"","link_parent_category":"","show_author":"","link_author":"","show_create_date":"","show_modify_date":"","show_publish_date":"","show_item_navigation":"","show_icons":"","show_print_icon":"","show_email_icon":"","show_vote":"","show_hits":"","show_noauth":"","alternative_readmore":"","article_layout":""}', 6, 0, 1, '', '', 1, 39, '{"robots":"","author":"","rights":"","xreference":""}', 0, '*', ''),
(33, 108, 'Local Government Finance: The Challenges of the 21st Century', 'gold-report-2', '', '<p>The 2nd Global Report of United Cities and Local Governments (UCLG) on Decentralization and Local Democracy analyzes the architecture of fiscal decentralization in one hundred and ten countries as well as in metropolitan areas. In the majority of these countries, local authorities are taking on more and more responsibilities in terms of public investment and in the provision of essential services for both economic development and the well being of populations.</p>\r\n\r\n<p>However with accelerating urbanization and the changing world context (climate change, increasing risk of natural disaster, migration, aging populations in certain countries), existing funding does not allow local governments to respond to the urbanization of poverty , nor to the growing need for investment. The economic and financial crisis which began in 2008 only worsened this divide. Beyond a simple state of affairs the Report proposes recommendations to strengthen local government finance.</p>\r\n\r\n<p><img style="display: block; margin-left: auto; margin-right: auto;" src="/images/stories/gold-reports/gold-reports-II.jpg.png" alt="" /></p>\r\n\r\n<p><a class="read_full" onclick="window.open(this.href,'''',''scrollbars=yes,resizable=yes,location=yes,menubar=yes,status=yes,toolbar=yes,width=,height=,left=''+(screen.availWidth/2-0)+'',top=''+(screen.availHeight/2-0)+'''');return false;" href="http://issuu.com/uclggold/docs/2010_executive_summary_baixa?mode=embed">Read full report</a></p>', '', 1, 0, 0, 2, '2011-11-10 22:39:25', 42, '', '2011-11-12 13:44:05', 42, 0, '0000-00-00 00:00:00', '2011-11-10 22:39:25', '0000-00-00 00:00:00', '', '', '{"show_title":"","link_titles":"","show_intro":"","show_category":"","link_category":"","show_parent_category":"","link_parent_category":"","show_author":"","link_author":"","show_create_date":"","show_modify_date":"","show_publish_date":"","show_item_navigation":"","show_icons":"","show_print_icon":"","show_email_icon":"","show_vote":"","show_hits":"","show_noauth":"","alternative_readmore":"","article_layout":""}', 4, 0, 2, '', '', 1, 40, '{"robots":"","author":"","rights":"","xreference":""}', 0, '*', ''),
(34, 109, 'Decentralization and Local Democracy in Asia Pacific', 'gold-reports-asia-pacific-1', '', '<p>It is our great pleasure to present the “First Global Report on Decentralization and Local Democracy” for Asia Pacific. We hope this report, which is the first of its kind, will help broaden and deepen knowledge about the current role of local governments and enrich national and international discussion on the relationship between decentralization and development.</p>\r\n\r\n<p>This first GOLD Asian Pacific Report, as we present it today, is part of the UCLG initiative to analyze the advances and possible reverses to local democracy and decentralization around the world on a regular basis. It is also the first global comparative analysis of the situation of local authorities in every region in the world.</p>\r\n\r\n<p><img style="display: block; margin-left: auto; margin-right: auto;" src="/images/stories/gold-reports/gold-reports-I.jpg" alt="" /></p>\r\n\r\n<p style="text-align: center;"><a class="read_full" onclick="window.open(this.href,'''',''scrollbars=yes,resizable=yes,location=yes,menubar=yes,status=yes,toolbar=yes,width=,height=,left=''+(screen.availWidth/2-0)+'',top=''+(screen.availHeight/2-0)+'''');return false;" href="http://issuu.com/uclggold/docs/gold_report_en?mode=embed">Read full report</a></p>', '', 1, 0, 0, 9, '2011-11-10 22:38:12', 42, '', '2011-11-14 14:48:29', 42, 0, '0000-00-00 00:00:00', '2011-11-10 22:38:12', '0000-00-00 00:00:00', '', '', '{"show_title":"","link_titles":"","show_intro":"","show_category":"","link_category":"","show_parent_category":"","link_parent_category":"","show_author":"","link_author":"","show_create_date":"","show_modify_date":"","show_publish_date":"","show_item_navigation":"","show_icons":"","show_print_icon":"","show_email_icon":"","show_vote":"","show_hits":"","show_noauth":"","alternative_readmore":"","article_layout":""}', 4, 0, 0, '', '', 1, 20, '{"robots":"","author":"","rights":"","xreference":""}', 0, '*', ''),
(37, 118, 'Decentralization and Local Democracy in the World (2)', 'gold-reports-2', '', '<p>It is our great pleasure to present the “First Global Report on Decentralization and Local Democracy”. We hope this report, which is the first of its kind, will help broaden and deepen knowledge about the current role of local governments and enrich national and international discussion on the relationship between decentralization and development.</p>\r\n<p>This first GOLD Report, as we present it today, is part of the UCLG initiative to analyze the advances and possible reverses to local democracy and decentralization around the world on a regular basis. It is also the first global comparative analysis of the situation of local authorities in every region in the world.</p>\r\n<p><img style="display: block; margin-left: auto; margin-right: auto;" src="/images/stories/gold-reports/gold-reports-I.jpg" alt="" /></p>\r\n<p style="text-align: center;"><a class="read_full" onclick="window.open(this.href,'''',''scrollbars=yes,resizable=yes,location=yes,menubar=yes,status=yes,toolbar=yes,width=,height=,left=''+(screen.availWidth/2-0)+'',top=''+(screen.availHeight/2-0)+'''');return false;" href="http://issuu.com/uclggold/docs/gold_report_en?mode=embed">Read full report</a></p>', '', -2, 0, 0, 2, '2011-05-02 11:48:08', 42, '', '2011-11-14 14:48:51', 0, 0, '0000-00-00 00:00:00', '2011-05-02 11:48:08', '0000-00-00 00:00:00', '', '', '{"show_title":"","link_titles":"","show_intro":"","show_category":"","link_category":"","show_parent_category":"","link_parent_category":"","show_author":"","link_author":"","show_create_date":"","show_modify_date":"","show_publish_date":"","show_item_navigation":"","show_icons":"","show_print_icon":"","show_email_icon":"","show_vote":"","show_hits":"","show_noauth":"","alternative_readmore":"","article_layout":""}', 1, 0, 0, '', '', 1, 0, '{"robots":"","author":"","rights":"","xreference":""}', 0, '*', ''),
(36, 117, 'Economic crisis in Algeria', 'news-africa-number-3', '', '<p><img src="http://www.newspapers24.com/images/category/algeria.jpg" border="0" width="200px" height="225" style="float: left; border: 0; margin: 10px;" /><span class="Apple-style-span" style="color: #363636; font-family: TitilliumText22LLight; font-size: 16px; line-height: 20px;">Economic crisis in Algeria</span></p>\r\n<p>Nunc congue, turpis sed ullamcorper elementum, nisl eros eleifend mauris, et tempor neque quam eu libero. Donec elementum, est vitae semper sagittis, eros justo posuere dui, at ultricies lectus nulla at neque. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nulla sem risus, elementum sit amet aliquam sed, consectetur eu ligula.</p>', '', 1, 0, 0, 43, '2011-11-08 13:47:16', 42, '', '2011-11-18 11:18:22', 42, 0, '0000-00-00 00:00:00', '2011-11-08 13:47:16', '0000-00-00 00:00:00', '', '', '{"show_title":"","link_titles":"","show_intro":"","show_category":"","link_category":"","show_parent_category":"","link_parent_category":"","show_author":"","link_author":"","show_create_date":"","show_modify_date":"","show_publish_date":"","show_item_navigation":"","show_icons":"","show_print_icon":"","show_email_icon":"","show_vote":"","show_hits":"","show_noauth":"","alternative_readmore":"","article_layout":""}', 2, 0, 0, '', '', 1, 0, '{"robots":"","author":"","rights":"","xreference":""}', 0, '*', ''),
(38, 119, 'Econoñic crisis in Asia', 'news-asia-pacific-2', '', '<p><img src="/images/stories/news/pellentesque.jpg" border="0" alt="" width="200px" style="float: left;margin:10px" /><span class="Apple-style-span" style="color: #363636; font-family: TitilliumText22LLight; font-size: 16px; line-height: 20px;">C''est dur la crise</span></p>', '', 1, 0, 0, 42, '2011-11-17 13:47:00', 42, '', '2011-11-18 15:44:03', 42, 0, '0000-00-00 00:00:00', '2011-11-17 13:47:00', '0000-00-00 00:00:00', '', '', '{"show_title":"","link_titles":"","show_intro":"","show_category":"","link_category":"","show_parent_category":"","link_parent_category":"","show_author":"","link_author":"","show_create_date":"","show_modify_date":"","show_publish_date":"","show_item_navigation":"","show_icons":"","show_print_icon":"","show_email_icon":"","show_vote":"","show_hits":"","show_noauth":"","alternative_readmore":"","article_layout":""}', 2, 0, 0, '', '', 1, 0, '{"robots":"","author":"","rights":"","xreference":""}', 0, '*', ''),
(39, 120, 'Key Indicators', 'key-indicators', '', '<div class="moduletable">\r\n	<h3>Key Indicators\r\n	</h3>\r\n</div>\r\n<p>As part of to ongoing work of the Observatory, UCLG periodically gathers key data on local government world wide.\r\n</p>\r\n<p>This data was first published in 2007, in a pocket book covering 82 countries. Following the data&rsquo;s revision in 2010 a second book was published covering 95 countries and including additional data field. This data collection was undertaken thanks to the support of Dexia Group and Cities Alliance.\r\n</p>\r\n<p>Four categories of data are available:\r\n</p>\r\n<ul>\r\n	<li>Population and Land\r\n	</li>\r\n	<li>Macroeconomic data\r\n	</li>\r\n	<li>Governance structures\r\n	</li>\r\n	<li>Public finance\r\n	</li>\r\n</ul>\r\n<p>The interactive data base allows filtering countries by common characteristics, comparisons between countries or simply access to county by country information. Both the 2007 and 2010 publications are available for download in PDF format.\r\n</p>\r\n<p>To advise us of errors in the data or to share comments on the data please contact us at the GOLD email address: gold@cities-localgovernments.org\r\n</p>\r\n<br />\r\n{loadposition key_indicators_article} ', '', 1, 0, 0, 30, '2011-11-29 10:32:28', 42, '', '2011-12-07 16:03:21', 42, 0, '0000-00-00 00:00:00', '2011-11-29 10:32:28', '0000-00-00 00:00:00', '', '', '{"show_title":"","link_titles":"","show_intro":"","show_category":"","link_category":"","show_parent_category":"","link_parent_category":"","show_author":"","link_author":"","show_create_date":"","show_modify_date":"","show_publish_date":"","show_item_navigation":"","show_icons":"","show_print_icon":"","show_email_icon":"","show_vote":"","show_hits":"","show_noauth":"","alternative_readmore":"","article_layout":""}', 21, 0, 0, '', '', 1, 277, '{"robots":"","author":"","rights":"","xreference":""}', 0, '*', ''),
(40, 121, 'Country Profiles', 'country-profiles', '', '<div class="moduletable">\r\n	<h3>Country Profiles\r\n	</h3>\r\n	<p>The UCLG Country Profiles provide an overview of the state of local government in 70 countries. They summaries the national context, territorial organization, state local democracy, central local relations, local responsibilities and local finance, and provide some basic statistics.\r\n	</p>\r\n	<p>The country sheets have been produced by local experts and UCLG&#39;s regional sections, with the support of UN-Habitat and the French Foreign and European Ministry.\r\n	</p>\r\n	<p>To advise us of errors in the data or to share comments on the information in the profiles please contact us at the GOLD email address: gold@cities-localgovernments.org\r\n	</p>\r\n</div>\r\n{loadposition Country_Profile}', '', 1, 0, 0, 7, '2011-12-01 14:39:30', 42, '', '2011-12-08 23:14:31', 42, 0, '0000-00-00 00:00:00', '2011-12-01 14:39:30', '0000-00-00 00:00:00', '', '', '{"show_title":"","link_titles":"","show_intro":"","show_category":"","link_category":"","show_parent_category":"","link_parent_category":"","show_author":"","link_author":"","show_create_date":"","show_modify_date":"","show_publish_date":"","show_item_navigation":"","show_icons":"","show_print_icon":"","show_email_icon":"","show_vote":"","show_hits":"","show_noauth":"","alternative_readmore":"","article_layout":""}', 53, 0, 0, '', '', 1, 107, '{"robots":"","author":"","rights":"","xreference":""}', 0, '*', ''),
(41, 126, 'Gold Report I', 'gold-report-i', '', '<p>The 1st Global Report on Decentralization and Local Democracy, published in 2008 is the first report of its kind. The goal of the report was to broaden and deepen knowledge on role of local governments and enrich the national and international discussion on the relationship between decentralization and development.\r\n</p>\r\n<p>GOLD I clearly show that the world is undergoing a quiet democratic revolution. In a world where more than half of humanity now lives in cities, local authorities are the key actors to solve the major contemporary challenges of all kinds.\r\n</p>\r\n<p>GOLD I provides a snap shot of the state of local democracy and decentralization in the mid-2000s, against which future advances and setback can be measured. The Report was made possible by the support of our partner institution mentioned below and the scientific coordination of the Research Network of Local Government of Europe (GRALE - University of Paris I).\r\n</p>\r\n<br />\r\n{loadposition Gold_Report_I_article} ', '', 1, 0, 0, 2, '2011-12-03 20:21:24', 42, '', '2011-12-06 13:42:15', 42, 0, '0000-00-00 00:00:00', '2011-12-03 20:21:24', '0000-00-00 00:00:00', '', '', '{"show_title":"0","link_titles":"0","show_intro":"0","show_category":"0","link_category":"0","show_parent_category":"0","link_parent_category":"0","show_author":"0","link_author":"0","show_create_date":"0","show_modify_date":"0","show_publish_date":"0","show_item_navigation":"0","show_icons":"0","show_print_icon":"0","show_email_icon":"0","show_vote":"0","show_hits":"0","show_noauth":"0","alternative_readmore":"","article_layout":""}', 5, 0, 1, '', '', 1, 13, '{"robots":"","author":"","rights":"","xreference":""}', 0, '*', ''),
(42, 128, 'Gold Report II', 'gold-report-ii', '', '<p>The 2nd Global Report of United Cities and Local Governments (UCLG) on Decentralization and Local Democracy analyzes the architecture of fiscal decentralization in one hundred and ten countries as well as in metropolitan areas. In the majority of these countries, local authorities are taking on more and more responsibilities in terms of public investment and in the provision of essential services for both economic development and the well being of populations.\r\n</p>\r\n<p>However with accelerating urbanization and the changing world context (climate change, increasing risk of natural disaster, migration, aging populations in certain countries), existing funding does not allow local governments to respond to the urbanization of poverty, nor to the growing need for investment. The economic and financial crisis which began in 2008 only worsened this divide. Beyond a simple state of affairs the Report proposes recommendations to strengthen local government finance.\r\n</p>\r\n<p>The Report was made possible by the support of our partner institution mentioned below and the scientific coordination of Jorge Mart&iacute;nez-V&aacute;zquez (Georgia State University) and Paul Smoke (New York University).\r\n</p>\r\n{loadposition Gold_Report_II} ', '', 1, 0, 0, 2, '2011-12-03 23:16:08', 42, '', '2011-12-05 12:12:44', 42, 0, '0000-00-00 00:00:00', '2011-12-03 23:16:08', '0000-00-00 00:00:00', '', '', '{"show_title":"0","link_titles":"0","show_intro":"0","show_category":"0","link_category":"0","show_parent_category":"0","link_parent_category":"0","show_author":"0","link_author":"0","show_create_date":"0","show_modify_date":"0","show_publish_date":"0","show_item_navigation":"0","show_icons":"0","show_print_icon":"0","show_email_icon":"0","show_vote":"0","show_hits":"0","show_noauth":"0","alternative_readmore":"","article_layout":""}', 29, 0, 0, '', '', 1, 145, '{"robots":"","author":"","rights":"","xreference":""}', 0, '*', '');
